app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
      ownershipEntityRefs:
      - group:default/smith-family
      userEntityRef: user:default/john-smith
backend:
  baseUrl: http://localhost:7007
  cors:
    credentials: true
    methods:
    - GET
    - HEAD
    - PATCH
    - POST
    - PUT
    - DELETE
    origin:
    - http://localhost:3000
    - http://localhost:7007
  reading:
    allow:
    - host: gist.githubusercontent.com
    - host: raw.githubusercontent.com
    - host: github.com
    - host: '*.github.com'
  database:
    client: better-sqlite3
    connection: ':memory:'
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  locations:
  - target: https://gist.githubusercontent.com/haarchri/aaa03c8d30db4b03aa601d59b1a9c066/raw/65044e49acd78e0368955a2ddaff52e53f6a24e4/catalog-info.yaml
    type: url
  rules:
  - allow:
    - Component
    - System
    - API
    - Resource
    - Location
  useUrlReadersSearch: true
crossplane:
  enablePermissions: false
# integrations:
#   github:
#   - host: github.com
#     token: ${GITHUB_TOKEN}
kubernetes:
  auth:
    providers:
      upbound: {}
  clusterLocatorMethods:
  - clusters:
    - authMetadata:
        upbound.io/organization: upbound-demo
        upbound.io/token: <token>
      authProvider: upbound
      name: solution-idp-non-prod-frontend-frontend
      skipMetricsLookup: true
      skipTLSVerify: true
      url: <url>
    type: config
  frontend:
    podDelete:
      enabled: true
  objectTypes:
  - configmaps
  - deployments
  - pods
  - services
  serviceLocatorMethod:
    type: multiTenant
  skipMetricsLookup: true
kubernetesIngestor:
  components:
    customWorkloadTypes:
    - apiVersion: v1alpha1
      group: aws.platform.upbound.io
      plural: xeks
      singular: xeks
    - apiVersion: v1alpha1
      group: aws.platform.upbound.io
      plural: xnetworks
      singular: XNetwork
    - apiVersion: v1alpha1
      group: aws.platform.upbound.io
      plural: xpodidentities
      singular: xpodidentity
    - apiVersion: v1
      group: pkg.crossplane.io
      plural: providers
    - apiVersion: v1alpha1
      group: platform.upbound.io
      plural: xsqlinstances
      singular: XSQLInstance
    - apiVersion: v1alpha1
      group: aws.platform.upbound.io
      plural: xsqlinstances
      singular: XSQLInstance
    - apiVersion: v1alpha1
      group: azure.platform.upbound.io
      plural: xsqlinstances
      singular: XSQLInstance
    - apiVersion: v1alpha1
      group: azure.platform.upbound.io
      plural: xnetworks
      singular: XNetwork
    disableDefaultWorkloadTypes: true
    enabled: true
    excludedNamespaces:
    - kube-public
    - kube-system
    - crossplane-system
    onlyIngestAnnotatedResources: false
    taskRunner:
      frequency: 10
      timeout: 600
  crossplane:
    claims:
      ingestAllClaims: true
    xrds:
      convertDefaultValuesToPlaceholders: true
      enabled: true
      ingestAllXRDs: true
      publishPhase:
        allowRepoSelection: false
        allowedTargets:
        - github.com
        git:
          repoUrl: github.com?owner=upbound&repo=solution-idp
          targetBranch: local-test
        target: github
      taskRunner:
        frequency: 10
        timeout: 600
  mappings:
    systemModel: cluster-namespace
organization:
  name: upbound
permission:
  enabled: false
techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local
